pipeline {
    agent any
    
    tools{
        maven 'Maven 3.6.0'
        jdk 'java1.8.0'
    }
    stages {
        stage('build') {
            steps {
                sh "mvn -B -DskipTests clean package"
            }
        }
        stage('Test') {
            sh "mvn test"
        }
        post{
            always{
                junit 'target/surefire-reports/*.xml'
            }
        }
    }
    stage('Deploy'){
        steps {
            // sh './jenkins/scripts/deliver.sh'
            sh 'java -jar target/my-app-1.0-SNAPSHOT.jar'
        }
    }
}
